name: The Green Machine
favicon: null
layout_spectrum: 0.49880902701988816
typography_spectrum: 0.5963496982585639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8cc63e'
    - '#056839'
    - '#629f82'
    - '#b0d4c4'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.8064170002471656
  rhythmicContrast: 0.607611441751942
purpose: []
